---
- name: Demonstrating variables in Jinja2 Loops
  hosts: localhost
  connection: local
  vars_files:
    - supermarket_vars.yaml
  gather_facts: no
  tasks:
    - name: Create the Jinja2 based template
      template: src=./supermarket_varloop.yaml.j2 dest=./supermarket_flat_output.yaml